function make_sh()
    open("submit.sh", "w") do io
        println(io, "#!/bin/bash")
        println(io, "#")
        println(io, "#SBATCH --job-name=prs_sim")
        println(io, "#")
        println(io, "#SBATCH --time=48:00:00")
        println(io, "#SBATCH --cpus-per-task=1")
        println(io, "#SBATCH --mem-per-cpu=20G")
        println(io, "#SBATCH --partition=owners")
        println(io, "")
        println(io, "#save job info on joblog:")
        println(io, "echo \"Job \$JOB_ID started on:   \" `hostname -s`")
        println(io, "echo \"Job \$JOB_ID started on:   \" `date `")
        println(io, "")
        println(io, "# load the job environment:")
        println(io, "module load julia")
        println(io, "module load python/3.9.0")
        # println(io, "module load R")
        # println(io, "module load gcc")
        # println(io, "module load cmake")
        println(io, "")
        println(io, "# run code")
        println(io, "echo 'running PRS genotype simulations'")
        println(io, "conda activate prs_sim")
        println(io, "python simulate_genotypes.py --sim 3 --threads 16")
        println(io, "")
        println(io, "#echo job info on joblog:")
        println(io, "echo \"Job \$JOB_ID ended on:   \" `hostname -s`")
        println(io, "echo \"Job \$JOB_ID ended on:   \" `date `")
        println(io, "#echo \" \"")
    end
end
make_sh()

